name: Build LaTeX document
on: [push, pull_request]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_REPO_PAT }}
          submodules: recursive
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        continue-on-error: true
        with:
          root_file: main.tex
          working_directory: ./tex
          args: -f -interaction=nonstopmode
          latexmk_use_xelatex: true
      - name: Upload LaTeX document to artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: PDF
          path: ./tex/main.pdf
      - name: Serve LaTeX document
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tex
